language: php
cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - vendor
install:
  - 'composer install'
php:
  - '7.0'
  - '7.1'
  - '7.2'
script:
  - 'composer lint'
  - 'composer sniff-summary'
  - 'composer sniff-errors-only'
  - 'composer test'
